language: python
python:
  - '3.9'

services:
  - postgresql

before_script:
  - psql -c 'create database noteshare;' -U postgres

install:
  - pip install docker-compose

script:
  - python manage.py collectstatic
  - python manage.py test
