# Generated by Django 3.2 on 2021-07-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='essa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
