# Generated by Django 3.2 on 2021-07-26 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_essa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='essa',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
