# Generated by Django 3.2 on 2021-08-15 15:06

from django.db import migrations, models
import notes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_text',
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_file',
            field=models.FileField(default=0, upload_to='notes', validators=[notes.validators.check_file_extension]),
            preserve_default=False,
        ),
    ]
