# Generated by Django 3.2 on 2021-05-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='notes'),
        ),
        migrations.AddField(
            model_name='note',
            name='content_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
