# Generated by Django 3.2 on 2021-05-18 21:22

from django.db import migrations, models
import notes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='notes', validators=[notes.validators.check_file_extension]),
        ),
    ]
