# Generated by Django 3.2 on 2021-05-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_note_content_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='autor',
            new_name='author',
        ),
    ]
