# Generated by Django 3.2 on 2021-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_rename_autor_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
