# Generated by Django 3.2 on 2021-07-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_note_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
